### ISSUE TITLE
ncm-network: nmstate: Doesn't handle "command" routes cleanly

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#1627]
`nmstate` itself doesn't appear to support them, which is probably fine, but the module tries to add them anyway, which results in an invalid config.

For example, we have a number of hosts with `unreachable` routes set:
```pan
"/system/network/interfaces/eth0/route/24/command" = "unreachable 10.0.0.0/8";
"/system/network/interfaces/eth0/route/25/command" = "unreachable 192.168.0.0/16";
```

The module doesn't deal with the missing address, netmask etc and writes out the following:
```yaml
  - destination: /32
    next-hop-interface: eth0
  - destination: /32
    next-hop-interface: eth0
```

Which results in the following from `nmstatectl apply`:
```
NmstateError: InvalidArgument: Invalid IP address : invalid IPv4 address syntax
```

Desired behaviour here is probably:
1. Try and catch these with a validation rule in the schema when `nmstate` is in use.
1. Ignore these kinds of rules at runtime with a suitable warning.
