### ISSUE TITLE
ncm-network: nmstate backend bonding option 'arp_ip_target' needs to be a string.

### ISSUE THREAD

**Issue by aka7** [quattor/configuration-modules-core#1639]
currently arp_ip_target is a list, nmstate doesn't like this, throws following error
`
Provide file is not valid NetworkState or NetworkPolicy: invalid type: sequence, expected a string
`
arp_ip_target in nmstate appears to be string,  looks like nmstate accepts comma separated ip as string.
so instead of 
```
  link-aggregation:
    mode: active-backup
    options:
      arp_ip_target:
      - 1.1.1.1
```
it should be 
```
  link-aggregation:
    mode: active-backup
    options:
      arp_interval: '8000'
      arp_ip_target:  '1.1.1.1, 1.1.2.1'
etc.
```

* The version of the component you are using (rpm -q $component)
nmc-network-23.6.0

* What OS version you are using (/etc/redhat-release or similar)
rhel 9.3

* Steps required to reproduce the problem
add bonding opts for arp_ip_target for bond0, i.e
```
/system/network/interfaces/bond0/bonding_opts
/system/network/interfaces/bond0/bonding_opts/arp_ip_target
/system/network/interfaces/bond0/bonding_opts/arp_ip_target/0 = 1.1.1.1
```
this will create 
/etc/nmstate/bond0.yml with 

```
  link-aggregation:
    mode: active-backup
    options:
      arp_ip_target:
      - 1.1.1.1
```

* Actual result versus expected result
```
  link-aggregation:
    mode: active-backup
    options:
      arp_ip_target: 1.1.1.1
```
