### ISSUE TITLE
ncm-network: nmstate backend policy routing removal does not work without downing the interface.

### ISSUE THREAD

**Issue by aka7** [quattor/configuration-modules-core#1643]
Currently the nmstate backend will run 'nmstatectl apply  /etc/nmstate/$interface.yml'

this works fine, except when there is config change where a policy route that was previously configured is no longer in config.  nmstate does not appear to remove them. Looks like nmstatectl apply just appends.

Only way this appears to work to down connection,  then apply the config.

* The version of the component you are using (rpm -q $component)
ncm-network-23.6.0-1

* What OS version you are using (/etc/redhat-release or similar)
```
# cat /etc/redhat-release
Red Hat Enterprise Linux release 9.3 (Plow)
```

* Steps required to reproduce the problem
add two 2 policy route to an interface so yaml file looks like this for routes. i.e
```
routes:
  config:
  - destination: 0.0.0.0/0
    next-hop-address: 10.10.10.65
    next-hop-interface: bond1
    table-id: '10'
  - destination: 10.10.10.64/28
    next-hop-interface: bond1
    table-id: '10'
  - destination: 10.10.12.0/24
    next-hop-interface: bond1
    table-id: '10'
```
3 routes added to table 10.

```
# nmstatectl apply /etc/nmstate/bond1.yml
# ip route show table 10
default via 10.10.10.65 dev bond1 proto static
10.10.10.64/28 dev bond1 proto static scope link
10.10.12.0/24 dev bond1 proto static scope link
```

now removed the route for dest 10.10.12.0/24 so file looks like this, 
```
routes:
  config:
  - destination: 0.0.0.0/0
    next-hop-address: 10.10.10.65
    next-hop-interface: bond1
    table-id: '10'
  - destination: 10.10.10.64/28
    next-hop-interface: bond1
    table-id: '10'
# nmstatectl apply /etc/nmstate/bond1.yml
```

nothing changes, removed route 10.10.10.0/24 still there.
```
# ip route show table 10
default via 10.10.10.65 dev bond1 proto static
10.10.10.64/28 dev bond1 proto static scope link
10.10.12.0/24 dev bond1 proto static scope link
```

down the interface first then apply
```
# nmcli conn down bond1
# nmstatectl apply /etc/nmstate/bond1.yml
# ip route show table 10
default via 10.10.10.65 dev bond1 proto static
10.10.10.64/28 dev bond1 proto static scope link
```

this could be bug with nmstate itself and I'm talking to redhat about this behavior but if we down the interface (like we do with ifcfg approach) then this works as expecteed.

* Actual result versus expected result

if a route is removed it should no longer be in the routing table after next ncm run.

**Comment by aka7** [comment]
Not documented well, but looks like adding a route entry of state: absent in config for each interface would do what we need here.

we might be able to work around this as the API is pretty generous with wildcards, so it looks like we could flush all of the existing routes for a device pretty easily:
 
~~~
•	Remove all route config entry that matches:
If any property is not defined in config absent route, it is treat as wildcard. For example, the following route entry removes all routes whose next hop is ‘eth1’.
    {
        Route.STATE: Route.STATE_ABSENT,
        Route.NEXT_HOP_INTERFACE: "eth1"
    }
~~~
 
https://nmstate.io/devel/api.html#route

so in yaml adding this seems do what the api does above.
```
routes:
  config:
  - next-hop-interface: eth1
    state: absent
```
