### ISSUE TITLE
ncm-network: nmstate ipoib support

### ISSUE THREAD

**Issue by kwaegema** [quattor/configuration-modules-core#1665]
current ncm-network using nmstate doesn't seem to support ipoib. 
@aka7  Is there a way to do this on EL9 using ncm-network?

I've seen two issues:
- interface got renamed
```
mlx5_core 0000:a1:00.0 ibp161s0: renamed from ib0
```
So ib0 in profile is not recognized as ib device, and it got treated as a bond interface :
```
[ERROR] Error '/usr/bin/nmstatectl apply /etc/nmstate/ib0.yml' output: [2024-02-28T16:29:13Z ERROR nmstate::ifaces::bond] InvalidArgument: Bond mode is mandatory for new bond interface: ib0
NmstateError: InvalidArgument: Bond mode is mandatory for new bond interface: ib0
```
When I manually rename the interface
```
ip link set dev ibp161s0 name ib0
```

this changes to
```

2024/03/01-16:53:11 [VERB] Getting output of command: /usr/bin/nmstatectl apply /etc/nmstate/ib0.yml
2024/03/01-16:53:11 [ERROR] Error '/usr/bin/nmstatectl apply /etc/nmstate/ib0.yml' output: NmstateError: InvalidArgument: Invalid propriety: unknown field `infiniband


```
- The generated yaml is not correct for IB devices
- 
I can manually start the ib interface using nmstatectl apply when i change the yaml

```
[root@node4230 ~]# diff -bu ib0.yml ib0.yml_ok
--- ib0.yml	2024-03-01 17:11:50.585099054 +0100
+++ ib0.yml_ok	2024-03-01 17:16:50.498239387 +0100
@@ -7,12 +7,13 @@
       prefix-length: 19
     dhcp: false
     enabled: true
-  link-aggregation:
-    port: []
   name: ib0
   profile-name: ib0
   state: up
-  type: bond
+  type: infiniband
+  infiniband:
+    mode: datagram
+    pkey: '0xffff'
 routes:
   config:
   - next-hop-interface: ib0
```

**Comment by aka7** [comment]
You are right in the fact that  nmstste module doesn't support this type.  In fact not sure if ncm-network supported it? Maybe maintainers can confirm?

There has been few fixes went into master that would have stopped it from being configured  as type bond though.

Regarding renaming of interface, nmstate module in ncm-network doesn't rename interfaces, so that's probably happening outside of ncm-network.

**Comment by aka7** [comment]
@kwaegema sorry,  to answer your question,  I think we can look to add the support in nmstate, if you provide full details of config needed for a  infiniband type configuration, 
and if we can separate the schema for nmstate only options, which @jrha is going to see if it's possible.

**Comment by stdweird** [comment]
@aka7 we will investigate, but this was all working in old ncm-network. but some of the details are handled by OFED config files and services, maybe something is also going wrong there as well (eg we are missing some rpms that handle this). there is interface renaming code in the old ncm-network though; not sure how this works anymore

**Comment by kwaegema** [comment]
Hi @aka7 
thanks! i don't find a lot of docs on ib config with nmstate, but this is a basic example what is needed:

https://github.com/nmstate/nmstate/blob/base/examples/infiniband_pkey_ipoib_create.yml
```
interfaces:
  - name: mlx5_ib0.80ff
    type: infiniband
    state: up
    infiniband:
      base-iface: mlx5_ib0
      mode: datagram
      pkey: '0x80ff'
```
right now I use this to get it running when i manually renamed the interface (that part is to be investigated)
```
interfaces:
- ipv4:
    address:
    - ip: 10.143.7.160
      prefix-length: 19
    dhcp: false
    enabled: true
  name: ib0
  profile-name: ib0
  state: up
  type: infiniband
  infiniband:
    mode: datagram
    pkey: '0xffff'
```
