### ISSUE TITLE
ncm-network: nmstate, add support for OVS bridges and ports

### ISSUE THREAD

**Issue by alvarosimon** [quattor/configuration-modules-core#1718]
OVS bridges and ports are not supported with ncm-network nmstate yet, just to add this example:

```
interfaces:
- name: eth100
  type: ovs-interface
  state: up
  ipv4:
    enabled: true
    address:
      - ip: 192.168.1.1
        prefix-length: 24
- name: br100
  type: ovs-bridge
  state: up
  bridge:
    options:
      stp: true
    port:
    - name: bond0
    - name: eth100
```
Including the new interface names for NetworkManager `ovs-bridge`and `ovs-interface`
