### ISSUE TITLE
ncm-network: nmstate: no IPIP tunnel support

### ISSUE THREAD

**Issue by kwaegema** [quattor/configuration-modules-core#1809]
currently generated config by nmstate:

```
interfaces:
- ipv4:
    enabled: false
  ipv6:
    enabled: false
  name: tun0
  profile-name: tun0
  state: down
routes:
  config:
```

old style config:
```
ONBOOT=yes
NM_CONTROLLED='no'
DEVICE=tun0
TYPE=IPIP
BOOTPROTO=none
MY_INNER_IPADDR=x.x.x.x/24
MY_OUTER_IPADDR=y.y.y.y
RESOLV_MODS=no
PEERDNS=no
```
